[package]
name = "rstream"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.9", features = ["attributes", "unstable"] }
async-trait = "0.1"

log = "0.4"
env_logger = "0.8"

typemap = "0.3"

rand = "0.8"

derivative = "2.2"

serde = { version="1.0", features = ["derive"] }
serde_yaml = "0.8"
bincode = "1.3"

anyhow = "1.0"

itertools = "0.10"

lazy_static = "1.4"

whoami = "1.1"

ssh2 = "0.9"
shell-escape = "0.1"

atomic_refcell = "0.1"

[dev-dependencies]
regex = "1.4.3"

[profile.release]
opt-level = 3
debug = false
lto = 'fat'
codegen-units = 1